---
- name: Ensure ~/.ssh exists
  file:
    path: "{{ ansible_facts.env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Restore ~/.ssh/config from iCloud private
  copy:
    src: >-
      {{ ansible_facts.env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs/dotfiles-private/ssh/config
    dest: "{{ ansible_facts.env.HOME }}/.ssh/config"
    mode: '0600'
  ignore_errors: true

- name: Restore shell dotfiles from iCloud private
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ item | basename }}"
    mode: '0644'
  with_fileglob:
    - >-
      {{ ansible_facts.env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs/dotfiles-private/shell/.*
  ignore_errors: true
